name: flutter_tutorial
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-182.2.beta <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_translate: ^4.0.2
  
  http: ^0.13.1
  email_validator: ^2.0.1
  
  url_launcher: ^6.1.2

  flutter_settings_screens: ^0.3.2-null-safety
  
  tutorial_coach_mark: ^1.2.3
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.3.2
  shared_preferences: ^2.0.13
  localstorage: ^4.0.0+1
  flutter_dotenv: ^5.0.2
  cloudinary_public: ^0.11.0
  image_picker: ^0.8.5+3
  # path_provider: ^2.0.10

  flutter_map: any
  geocoder: ^0.2.1
  tuple: any
  latlng: any
  positioned_tap_detector_2: ^1.0.0
  transparent_image: any
  async: ^2.1.0
  flutter_image: ^3.0.0
  vector_math: ^2.0.0
  proj4dart: any
  meta: ^1.1.0
  collection: ^1.14.0
  geolocator: ^8.2.0

  flutter_pdfview: ^1.0.4
  permission_handler: any

  file_picker: any
  path: ^1.7.0
  path_provider: any
  syncfusion_flutter_charts: ^20.1.59
  simple_animations: ^4.0.2


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/en.json
    - assets/i18n/es.json
    - assets/i18n/ca.json

 